### ISSUE TITLE
Products not in Atom CAP v1.2 format?

### ISSUE THREAD

**Issue by rcmcdonald91** [jbuitt/nwws-python-client#1]
This issue might not technically be related to your python client, however there is very little documentation and hardly anybody discussing NWWS-OI on the internet.

CAP v1.1 formatted feeds are provided via county-level Atom feeds at https://alerts.weather.gov/

Apparently, NWWS-OI is supposed push Atom-based CAP v1.2 messages. However, the product files generated by your script are obviously not Atom-based and are just line-delimited txt files. Is this an artifact of your parsing routine or intrinsic to the messages provided by NWWS-OI? It would be very nice if the txt files produced by your script would be Atom-based CAP v1.2 messages to ease parsing by a PAN_RUN script.

**Comment by rcmcdonald91** [comment]
"NWWS-OI and SBN/NOAAPORT Channel 201 will not have the CAP v1.2 format at this time. NWWS requires native CAP v1.2 generation from the Weather Forecast Office (WFO) Advanced Weather Interactive Processing System (AWIPS) for NWS Enterprise wide dissemination."

**Comment by jbuitt** [comment]
Thank you for that information. Sorry it's taken me so long to reply. 

Yes, unfortunately the NWWS only pushes the product text data at this time. Once the NWWS starts pushing the products using CAP v1.2, I will gladly adjust the Python script to account for the change. Please let me know if you need anything else.

Thanks
